[project]
name = "mman-tool"
version = "0.2.1"
description = "mange your files migration"
license = "MIT"
readme = "README.md"
authors = [
    { name = "johnwink", email = "johnwink1998@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "myfind",
]

[project.scripts]
mm = "mman.cli:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"


[tool.uv.build-backend]
module-name = "mman"
module-root = "src"

[tool.uv.sources]
myfind = { git = "https://github.com/wink-code/myfind.git" }

[dependency-groups]
dev = [
    "pyright>=1.1.414",
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes (未使用变量, 未定义名字)
    "I",    # isort (import 排序)
    "UP",   # pyupgrade (旧语法升级)
    "B",    # flake8.bugbear (常见bug模式)
    "SIM",  # flake8-simplify (可简化的写法)
    ]
ignore = [
    "E501", # 行太长, 交给formatter 处理
    ]
